# Generated by Django 4.2.4 on 2023-10-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
