# Generated by Django 4.2.4 on 2023-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the download item', max_length=255)),
                ('file', models.FileField(help_text='Choose a file to upload', upload_to='downloadsPage/')),
            ],
            options={
                'verbose_name': 'Download Item',
                'verbose_name_plural': 'Download Items',
            },
        ),
        migrations.CreateModel(
            name='Video_Ea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the video', max_length=255)),
                ('youtube_url', models.URLField(help_text='Enter the YouTube video URL')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
