# Generated by Django 4.2.4 on 2023-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_downloaditem_video_ea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_ea',
            name='youtube_url',
            field=models.TextField(),
        ),
    ]
