# Generated by Django 4.2.4 on 2023-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_video_ea_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_ea',
            name='youtube_url',
            field=models.URLField(help_text='Enter the YouTube video URL'),
        ),
    ]
